version: '3'


services:
  mysqldb:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    volumes:
      - mysqldb_volume:/var/lib/mysql
      - ./src/main/resources/db/init.sql:/data/application/init.sql
    restart: always

    ports:
      - '3316:3306'
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_PORT='3306'


  bot:
    build: .
    restart: always
    environment:
      - TZ=Europe/Moscow
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    links:
      - mysqldb
    depends_on:
      - mysqldb

volumes:
  mysqldb_volume:
    driver: local